packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.0.0
    '@types/node': ^22.17.2
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.37.0
    glob: ^11.0.3
    prettier: ^3.6.2
    rollup: ^4.46.2
    typescript: ^5.9.2
    vitest: ^3.2.4
