packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.6.0
    '@types/node': ^22.18.10
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.37.0
    glob: ^11.0.3
    prettier: ^3.6.2
    rollup: ^4.52.5
    typescript: ^5.9.3
    vitest: ^3.2.4
  prod:
    '@pixpilot/object': ^1.0.3
  peer:
    '@supabase/supabase-js': ^2.75.1
    zod: 4.1.12
