/**
 * Headers that must not be forwarded between a client and an upstream
 * Supabase Function. They are either connection-specific, runtime-managed, or
 * expose details about the original client or proxy infrastructure.
 */
export const defaultRequestHeadersToRemove = [
  'connection',
  'keep-alive',
  'transfer-encoding',
  'te',
  'trailer',
  'upgrade',
  'proxy-authorization',
  'proxy-authenticate',
  'expect',
  'host',
  'content-length',
  'content-encoding',
  'set-cookie',
  'cf-connecting-ip',
  'cf-ipcountry',
  'cf-ray',
  'cf-visitor',
  'cf-request-id',
  'cf-worker',
  'forwarded',
  'via',
  'x-forwarded-for',
  'x-forwarded-proto',
  'x-forwarded-host',
  'x-forwarded-port',
  'x-forwarded-server',
  'x-real-ip',
  'upgrade-insecure-requests',
  'sec-fetch-mode',
  'sec-fetch-site',
  'sec-fetch-user',
  'sec-ch-ua',
  'sec-ch-ua-arch',
  'sec-ch-ua-bitness',
  'sec-ch-ua-full-version',
  'sec-ch-ua-full-version-list',
  'sec-ch-ua-mobile',
  'sec-ch-ua-model',
  'sec-ch-ua-platform',
  'sec-ch-ua-platform-version',
  'sec-ch-ua-wow64',
] as const;
