# .github/workflows/release.yml

name: Release Package

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  ci:
    name: Run CI Checks
    uses: ./.github/workflows/ci.yml

  release:
    name: Create Release and Publish
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Generate bot app token
        id: app_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RELEASER_ID }}
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          registry-url: 'https://registry.npmjs.org'
          build: 'false'

      - name: Release
        uses: pixpilot/changesets-autopilot@v1
        with:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
